In [1]:
import numpy as np
from time import process_time


In [2]:
python_lst = [i for i in range(10000)]

In [6]:
start_time = process_time()

In [3]:
python_lst = [i+5 for i in python_lst]

In [4]:
end_time = process_time()

In [12]:
print(end_time - start_time)

0.0


In [13]:
np_array = np.array([i for i in range(10000)])
start_time = process_time()
np_array = np_array+5
end_time =process_time()
print(end_time - start_time)

0.0


In [15]:
#np array

In [17]:
list1 = [1,2,3,4,5]
print(list1)
type(list1)

[1, 2, 3, 4, 5]


list

In [22]:
np_array = np.array([1,2,3,4,5])
print(np_array)
type(np_array)
print(np_array.shape)

[1 2 3 4 5]
(5,)


In [ ]:
#create 1D array

In [23]:
array= np.array([1,2,3,4,5])

In [24]:
array.shape

(5,)

In [26]:
array2 = np.array([[1,2,3,4] , [4,5,6,7]])

In [27]:
array2.shape

(2, 4)

In [28]:
print(array2)

[[1 2 3 4]
 [4 5 6 7]]
