In [1]:
import numpy as np
from time import process_time


In [2]:
python_lst = [i for i in range(10000)]

In [6]:
start_time = process_time()

In [3]:
python_lst = [i+5 for i in python_lst]

In [4]:
end_time = process_time()

In [12]:
print(end_time - start_time)

0.0


In [13]:
np_array = np.array([i for i in range(10000)])
start_time = process_time()
np_array = np_array+5
end_time =process_time()
print(end_time - start_time)

0.0


In [15]:
#np array

In [17]:
list1 = [1,2,3,4,5]
print(list1)
type(list1)

[1, 2, 3, 4, 5]


list

In [22]:
np_array = np.array([1,2,3,4,5])
print(np_array)
type(np_array)
print(np_array.shape)

[1 2 3 4 5]
(5,)


In [ ]:
#create 1D array

In [23]:
array= np.array([1,2,3,4,5])

In [24]:
array.shape

(5,)

In [26]:
array2 = np.array([[1,2,3,4] , [4,5,6,7]])

In [27]:
array2.shape

(2, 4)

In [28]:
print(array2)

[[1 2 3 4]
 [4 5 6 7]]


In [34]:
array3= np.array([[[1,2,3] , [3,4,5]],
                  [[1,2,3] , [4,5,6]]])

In [35]:
array3.shape

(2, 2, 3)

In [36]:
array2 = np.array([[1,2,3,4] , [4,5,6,7]] , dtype = float)

In [37]:
print(array2)

[[1. 2. 3. 4.]
 [4. 5. 6. 7.]]


In [43]:
x = np.zeros((3,2))

In [44]:
print(x)

[[0. 0.]
 [0. 0.]
 [0. 0.]]


In [45]:
x = x.T

In [46]:
print(x)

[[0. 0. 0.]
 [0. 0. 0.]]


In [47]:
y = np.ones((3,3))

In [48]:
print(y)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [49]:
z = np.full((4,5) , 8)
print(z)

[[8 8 8 8 8]
 [8 8 8 8 8]
 [8 8 8 8 8]
 [8 8 8 8 8]]


In [50]:
#create identity metrics

In [53]:
a = np.eye(3)

In [54]:
print(a)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
#create nmpy array wit random nbers

In [105]:
b = np.random.randint(10 ,100,(3,3))
print(b)

[[34 48 89]
 [28 56 62]
 [34 25 16]]


In [112]:
d = np.linspace(10 , 30 , 5)
print(d)

[10. 15. 20. 25. 30.]
